'
on:
  push:
    branches:
      - "main"
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run the scripts
        run: |
          cd lichess
          sh script.sh
'