on:
  push:
    branches:
      - "main"
jobs:
  example-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts
    steps:
      - name: Make the script files executable
        run: chmod +x ./lichess/script.sh
      - name: Run the scripts
        run: |
          sh ./lichess/script.sh