on:
  push:
    branches:
      - "main"
jobs:
  example-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lichess
    steps:
      - name: Run the scripts
        run: |
          sh script.sh